name: majimo_timer
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  slide_digital_clock: ^1.0.0
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  fabexdateformatter: ^1.0.5
  bottom_bar: ^1.2.3+1
  animated_text_kit: ^4.2.1
  animations: ^2.0.1
  auto_animated: ^3.0.0
  delayed_widget: ^1.1.1
  expandable_slider: "^1.0.0"
  flutter_staggered_animations: "^1.0.0"
  day_night_time_picker: ^1.0.2
  easy_localization: ^2.3.3
  easy_localization_loader: any
  shared_preferences: any
  preferences: any


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/translations/langs.csv

  fonts:
    - family: M-plus
      fonts:
        - asset: assets/fonts/MPLUS1p-Bold.ttf
          style: normal
          weight: 500

        - asset: assets/fonts/MPLUS1p-Medium.ttf
          style: normal
          weight: 400
        - asset: assets/sun.png
        - asset: assets/moon.png


intl: ^0.15.8