name: majimo_timer
description: A new Flutter project.

publish_to: 'none'

version: 0.4.4+beta

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  app_links: ^2.2.0
  auto_size_text: ^3.0.0
  auto_size_text_pk: ^3.0.0-nullsafety
  awesome_notifications: ^0.6.17
  circular_countdown_timer: ^0.2.0
  cupertino_back_gesture: ^0.1.0
  cupertino_icons: ^1.0.2
  dart_date: ^1.1.0
  day_night_time_picker: ^1.0.3+1
  dismissible_page: ^0.6.3
  draggable_home: ^1.0.2
  duration_picker: ^1.1.0+1
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0
  expandable_widgets: ^1.0.2
  flag: ^5.0.1
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_color: ^2.0.0
  flutter_fader: ^2.0.0+1
  flutter_grid_button: ^2.0.0
  flutter_hooks: ^0.18.0
  flutter_overboard: ^3.1.1
  flutter_styled_toast: ^2.0.0
  flutter_windowmanager: ^0.2.0
  freezed_annotation: ^1.1.0
  fullscreen: ^1.0.3
  hooks_riverpod: ^1.0.0
  json_annotation: ^4.4.0
  lottie: ^1.2.1
  modal_bottom_sheet: ^2.0.0
  percent_indicator: ^3.4.0
  quds_ui_kit: ^0.0.7+5
  quick_actions: ^0.6.0+8
  ripple_backdrop_animate_route: ^1.0.0
  rive: ^0.8.1
  simple_animations: ^4.0.1
  slide_digital_clock: ^1.0.2
  stop_watch_timer: ^1.3.1
  url_launcher: ^6.0.20
  wakelock: ^0.5.6
  webview_flutter: ^3.0.1

dev_dependencies:
  build_runner: ^2.1.7
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.2
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  pedantic_mono: ^1.15.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter_native_splash:
  image: assets/splash/splash.png
  color: "#ff6600"
  color_dark: "#ff5521"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/splash/
    - assets/l10n/

  fonts:
    - family: M-plus-B
      fonts:
        - asset: assets/fonts/MPLUS1p-Bold.ttf
          style: normal
          weight: 500

    - family: M-plus-M
      fonts:
        - asset: assets/fonts/MPLUS1p-Medium.ttf
          style: normal
          weight: 400
